name: 部署到 GitHub Pages

on:
  # 當推送到 main 分支時運行
  push:
    branches: [main]

  # 允許從 Actions 頁籤手動運行此工作流程
  workflow_dispatch:

# 設置 GitHub Token 的權限，以允許部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 僅允許同一時間進行一次部署，跳過運行中的和最新隊列間的執行
# 但是，不會取消正在執行的任務，確保這些生產部署可以完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 構建任務
  build:
    runs-on: ubuntu-latest
    steps:
      # 檢出程式碼
      - name: 檢出程式碼
        uses: actions/checkout@v4

      # 設置 Node.js 環境
      - name: 設置 Node.js 環境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 設置 pnpm
      - name: 設置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.9

      # 安裝依賴
      - name: 安裝依賴
        run: pnpm install --frozen-lockfile

      # 構建項目
      - name: 構建項目
        run: pnpm run build

      # 上傳構建產物
      - name: 上傳構建產物
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # 部署任務
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
